server:
  port: 8111
  servlet:
    context-path: /scalp

mq:
  env: local
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scalp_system?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: scalp
    password: 123
  #redis 配置
  redis:
    database: 0
    host: 103.140.150.20
    open: true # 是否开启redis缓存
    lettuce:
      pool:
        max-active: 500   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 100     #最大等待连接中的数量,设 0 为没有限制
        max-wait: 3000  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 50     #最小等待连接中的数量,设 0 为没有限制
    password: 123
    port: 6370
  task:
    pool:
      corePoolSize: 5
      maxPoolSize: 10
      keepAliveSeconds: 60
      queueCapacity: 100
      threadNamePrefix: ytoThreadPool
  #MQ配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #开启发送确认回调
    publisher-confirm-type: correlated
    #开启发送失败返回
    publisher-returns: true
    listener:
      type: simple
      simple:
        #指定最小的消费者数量
        concurrency: 1
        max-concurrency:
        #消息确认接收 确认模式---auto自动确认   MANUAL手动确认  none不确认
        acknowledge-mode: auto
    #支持消息的确认与返回
    template:
      mandatory: true
    connection-timeout: 15000

#  rabbitmq:
#    port: 5672
#    host: 127.0.0.1
#    virtual-host: /
#    #并发量的配置
#    listener:
#      concurrency: 10.0
#      max-concurrency: 20.0
#      prefetch: 5.0
#    password: guest
#    username: guest


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/hrkj/scalp/*/mapper/xml/*Mapper.xml
  type-aliases-package: com.hrkj.scalp.*.entity
  global-config:
    db-config:
      id-type: auto

#Mybatis输出sql日志
logging:
  level:
    org.jeecg.modules.system.mapper : debug

#basic:
#  info:
#    mq:
#      exchange:
#        name: ${mq.env}:basic:info:mq:exchange
#      queue:
#        name: '${mq.env}:basic:info:mq:queue '
#      routing:
#        key:
#          name: ${mq.env}:basic:info:mq:routing:key


